id: d2f7ee5a92754b4e8241cffdd6b2aef3
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_563-Upholding_the_Great_Secret_Mantra-v1
  language: en
  author: ''
  volume: {}
